### ISSUE TITLE
LRM clarification for operator associativity

### ISSUE THREAD

**Issue by nickbattle** [overturetool/language#47]
Overture issue #702 raises some questions about the associativity of relative operators (in particular, "=" with boolean arguments) and the "**" exponentiation operator.

It may be possible to add some clarification on both issues to the LRM.

**Comment by nickbattle** [comment]
I suggest that an addition is made to section "C.7 Grouping", which currently describes the associativity of the families of operators. We could add something like this:

"Note: the `'='` operator is in the Relations family, which does not have specified grouping. However, it is possible to construct a meaningful expression with a chain of `'='` operators comparing Boolean values, such as `true = 3 = 3`. This is parsed as `true = (3 = 3)` - i.e. the `'='` operator has right grouping.

The `'**'` operator is always treated as an iterator for the purpose of grouping, and is therefore a member of the Combinators family and has right grouping."

How does that sound?

**Comment by paulch42** [comment]
** has to group to the left. `f**m**n` if left grouped, i.e. `(f**m)**n`, means iterate f m*n times. If grouped to the right, i.e. `f**(m**n)` it is guaranteed to always fail type checking.

**Comment by nickbattle** [comment]
The `**` operator has several overloaded meanings, unfortunately - it can mean numeric exponentiation, function iteration or map iteration. In each case, the operand on the RHS has to be numeric (real or nat). So it's true that right-grouped function and map iteration cannot be written without brackets (as things stand) because the rightmost pair yields a function or map. But the numeric exponentiation convention is that `**` groups to the right, apparently.

We have a conflict because of the overloading and the fact that the natural grouping for the different cases is different? But grouping is a syntactic matter, which cannot know the types of the operands. The current Overture/VDMJ interpretation is consistent with VDMTools, at least.

Is this causing a problem, other than the irritation of needing brackets in some cases?

**Comment by nickbattle** [comment]
Original issue here: https://github.com/overturetool/overture/issues/702

**Comment by paulch42** [comment]
Ok, I forgot about the numeric use of `**`.

If right grouping is the standard mathematical convention then your wording sounds good.

In practice I can't think of a scenario where I would want to chain function/map iteration, and if I did adding parentheses is not a burden.

**Comment by nickbattle** [comment]
This change is now in the editing branch of the LRM via merged PR. I think this issue can now be closed.

**Comment by kgpierce** [comment]
Issue closed after LRM update.
