### ISSUE TITLE
RM: Treat anonymous functions as total instead of partial

### ISSUE THREAD

**Issue by donbex** [overturetool/language#55]
##### Identification of the Originator

Alessandro Pezzoni (Anaplan Limited)

##### Target of the request, defining the affected components of the language definition 

The type checking of anonymous (lambda) functions.

##### Motivation for the request

Anonymous functions are currently treated as partial functions. However, the
syntax for lambda expressions does not allow the stating of pre and post
conditions, which means that any implicit assumption on the inputs and output
of the function will go unspecified.

This implies that only total functions can be safely specified using a lambda
expression.

##### Description of the request

For all intents and purposes, treat anonymous functions as total.

###### description of the modification

**Language Reference Manual**: Section 6.16, "The Lambda Expression", should
explicitly state whether functions defined through a lambda expression are
treated as total or partial. _This is not currently the case, and a change
should be made regardless of whether this request is accepted or rejected._

**Static semantics**: The type checker should treat anonymous functions as
total.

###### benefits from the modification

Reducing the likelihood of implicit assumptions and constraints not being
specified.

###### possible side effects

Minimal. A total function is accepted wherever a partial function is accepted,
so the only changes required to existing specifications would be where the type
of the lambda is explicitly stated, e.g. when declaring the function as
a value.

##### A test suite for validation of the modification in the executable models (if appropriate).

The following VDM-SL specification should type check.

```
functions

  filter[@a]: seq of @a * (@a +> bool) -> seq of @a
  filter(xs, p) == [ x | x in seq xs & p(x) ];

values

  S = [1, 2, 3, 4];

  T = filter[int](S, lambda x : int & x mod 2 = 0);
```

Further examples can be provided as needed if the request is accepted.

**Comment by tomooda** [comment]
The LB has decided to advance the RM. An owner of this RM will be shortly assigned.

**Comment by tomooda** [comment]
I agree that whether a lambda is total or partial should be explicitly stated in the LRM.
I'm afraid that typing lambda as a total function is too restrictive.
It'll enforce that every lambda expression must be totally defined.
Possible uses of lambda could be restricted by typing it as a total function.

Another way to use lambda in place of a total function is to relax the weak type checking and generate a proof obligation to prove the specific lambda is actually totally defined instead of emitting a type error.
The PO would look like
```
forall x : int & is_(x mod 2 = 0, bool)
```
which would anyway be generated if this RM is applied.

**Comment by nickbattle** [comment]
> Possible uses of lambda could be restricted by typing it as a total function.

This isn't easy currently, if I understand what you mean. The type checker doesn't regard (say) a `nat->nat` value as _possibly_ a `nat+>nat` value, so an assignment to that type fails. I think this is right: a partial function isn't a total function (whereas a total function is a partial function in a sense, albeit with total coverage).

Can you give an example of how we can do this?

**Comment by nickbattle** [comment]
These examples raise errors:
```
-- Tests for partial function conversion
values
	T : nat +> nat = lambda x:nat & x+1;

functions
	total: () +> (nat +> nat)
	total() ==
		lambda x:nat & x+1;

Expression does not match declared type, Declared: (nat +> nat), Expression: (nat -> nat1)
Function returns unexpected type, Actual: (nat -> nat1), Expected: (nat +> nat)
```

**Comment by tomooda** [comment]
In the following spec, the current type checker of VDMJ4 emits a type error at the definition of f3.
The functions `f1`, `f2` and `f3` are the same function except for their static types.
I think this is an example of a function that is statically typed as a partial function can possibly be a value of a total function type.

```
functions
f : int +> int
f(x) == x

values
f1 : int -> int = f;
f2 : int +> int = f;
f3 : int +> int = f1
```

If the natural domain of a partial function is a proper subset of its domain type (e.g. functions defined with pre clauses), the partial function has no chance to be a total function, and therefore the type checker should raise a type error when it's used in a place of a total function.
However, some total functions are statically typed as partial functions like the above example.
I think an interpreter may emit a warning at the definition of f3, and may generate a PO like
```
f3: total function obligation in 'DEFAULT' (t.vdmsl) at line 8:1
(forall x:int &
  is_(f3(x), int))
```
that is the same as the PO for the totality of function `f` at  the line 2.

**Comment by nickbattle** [comment]
Ah yes, I see. I note that in my version of VDMTools, this spec generates a PO for f3, `is_(f1,int +> int)` (as a subtype obligation). I'll take a closer look at VDMJ's checking here.

**Comment by nickbattle** [comment]
So with the obvious tweak to the type comparator, your example spec now behaves like VDMTools - that is, it's clean, but the POG requires that the f3 assignment is total:
```
> pog
Generated 2 proof obligations:

Proof Obligation 1: (Unproved)
f: total function obligation in 'DEFAULT' (test.vdm) at line 2:1
(forall x:int &
  is_(f(x), int))

Proof Obligation 2: (Unproved)
f3: subtype obligation in 'DEFAULT' (test.vdm) at line 8:19
is_(f1, (int +> int))

```
I've pushed the changes to the development branch of VDMJ, so we can do more testing. But this looks reasonable.

**Comment by tomooda** [comment]
@nickbattle Amazing! Your quick coding always fascinates me. 😃 
@donbex Do you think this would help you?

**Comment by nickbattle** [comment]
@donbex I'll need to try the same change in Overture (which is what you presumably need?), but it should work the same way.

**Comment by nickbattle** [comment]
@idhugoid I've just pushed the same change to the ncb/development branch of Overture.

**Comment by donbex** [comment]
@nickbattle Our specification type checks correctly with your changes in https://github.com/overturetool/overture/commit/fefa1b3b07206218edcd2216e2c0e819c3a6c3ff, so that should be sufficient for us.

**Comment by tomooda** [comment]
The Overture tool with https://github.com/overturetool/overture/commit/fefa1b3b07206218edcd2216e2c0e819c3a6c3ff already addresses the issue with the original type checking. So, this RM is executed and completed.
